blank_issues_enabled: false
contact_links:
  - name: I am Shypd's Chief Tinkerer
    url: https://github.com/mepragya-code/Shypd-updates/issues/new/choose
    about: If you think you can help us improve our product, please dont hesitate to raise an issue.